stages:
  - build

variables:
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH

build centos docker image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE_LATEST_TAG: centos7
    IMAGE_FULL_TAG: centos7-$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin "$CI_REGISTRY"
  script:
    - docker pull "$IMAGE_NAME:$IMAGE_LATEST_TAG"
    - docker build -t "$IMAGE_NAME:$IMAGE_FULL_TAG" -t "$IMAGE_NAME:$IMAGE_LATEST_TAG" -f docker/linux/Dockerfile.centos .
    - docker push "$IMAGE_NAME:$IMAGE_FULL_TAG"
    - docker push "$IMAGE_NAME:$IMAGE_LATEST_TAG"
  tags:
    - cura
    - linux
    - docker
#  only:
#    - master

#build windows docker image:
#  stage: build
#  variables:
#    IMAGE_LATEST_TAG: windows-core-1809
#    IMAGE_FULL_TAG: windows-core-1809-$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
#  before_script:
#    - echo "$env:CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin "$env:CI_REGISTRY"
#  script:
#    - docker build -t "${env:IMAGE_NAME}:${env:IMAGE_FULL_TAG}".toLower() -t "${env:IMAGE_NAME}:${env:IMAGE_LATEST_TAG}".toLower() -f docker/windows/Dockerfile.vs2015 .
#    - docker push "${env:IMAGE_NAME}:${env:IMAGE_FULL_TAG}".toLower()
#    - docker push "${env:IMAGE_NAME}:${env:IMAGE_LATEST_TAG}".toLower()
#  tags:
#    - cura
#    - windows
#    - powershell
#  only:
#    - master
